## Understanding Tensor from Docs

>A __torch.Tensor__ is a multi-dimensional matrix containing elements of a single data type.

[Tensor Docs](https://pytorch.org/docs/stable/tensors.html "Go and learn")

In [1]:
import torch

### Tensor Creation

[Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops "Learn to create first")

1. To create a tensor with pre-existing data, use ```torch.tensor()```.

2. To create a tensor with specific size, use ```torch.*```.

3. To create a tensor with the same size (and similar types) as another tensor, use ```torch.*_like```.

4. To create a tensor with similar type but different size as another tensor, use ```tensor.new_*```.

In [2]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [7]:
# torch.tensor.item() to get python number 
print(x[1][2])

x[1][2].item()

tensor(6)


6

### Tensor Views

PyTorch allows a tensor to be a View of an existing tensor. View tensor shares the same underlying data with its base tensor. Supporting View avoids explicit data copy, thus allows us to do fast and memory efficient reshaping, slicing and element-wise operations.

<p style="color:red">Taking a view of contiguous tensor could potentially produce a non-contiguous tensor. </p>

In [8]:
base = torch.tensor([[0, 1],[2, 3]])
base.is_contiguous()

True

In [9]:
t = base.transpose(0, 1)  
# `t` is a view of `base`. No data movement happened here.
# View tensors might be non-contiguous.
t.is_contiguous()

False

In [10]:
# To get a contiguous tensor, call `.contiguous()` to enforce
# copying data when `t` is not contiguous.
c = t.contiguous()

 ---

Create a new tensor from existing

1. **new_tensor**: Returns a new Tensor with ```data``` as the tensor data. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.
<p style="color:red">If you have a numpy array and want to avoid a copy, use torch.from_numpy().</p><br>
2. **new_full**: Returns a Tensor of size ```size``` filled with fill_value.
3. **new_empty**: Returns a Tensor of size size filled with uninitialized data.
4. **new_ones**: Returns a Tensor of size size filled with 1
5. **new_zeros**: Returns a Tensor of size size filled with 0


In [28]:
# Test tensor
tensor = torch.tensor((2,2), dtype=torch.float32)

# 1 new_tensor
data = [[0, 1], [2, 3]]
tensor.new_tensor(data = data)

tensor([[0., 1.],
        [2., 3.]])

In [29]:
# 2. new_full
tensor.new_full(size = (3, 4), fill_value = 3.141592)

tensor([[3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416, 3.1416]])

In [30]:
# 3. new_empty
tensor.new_empty((2,3))

tensor([[-1.9941e-31,  4.5902e-41, -1.9941e-31],
        [ 4.5902e-41,  0.0000e+00,  0.0000e+00]])

In [31]:
# 4. new_ones 
# 5. new_zeros
print(tensor.new_ones((2, 3)))
tensor.new_zeros((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[0., 0., 0.],
        [0., 0., 0.]])

 ---

**Computational Graph**

```backward(gradient=None, retain_graph=None, create_graph=False)```

Computes the gradient of current tensor w.r.t. graph leaves.

The graph is differentiated using the chain rule. If the tensor is non-scalar (i.e. its data has more than one element) and requires gradient, the function additionally requires specifying gradient. It should be a tensor of matching type and location, that contains the gradient of the differentiated function w.r.t. self.

In [45]:
x = torch.tensor([5.,5.], requires_grad=True)

In [46]:
out = x.pow(2).sum()

In [47]:
out.backward() 

In [48]:
x.grad

tensor([10., 10.])

---

**torch.tensor.expand()**

In [51]:
x = torch.tensor([[1], [2], [3]])
x.size()

torch.Size([3, 1])

In [52]:
x.expand(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [53]:
x.expand(-1, 4)   
# -1 means not changing the size of that dimension

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

---

**is_leaf**

All Tensors that have ```requires_grad``` which is **False** will be leaf Tensors by convention.

For Tensors that have ```requires_grad``` which is **True**, they will be leaf Tensors if they were created by the user. This means that they are not the result of an operation and so ```grad_fn``` is None.

Only leaf Tensors will have their ```grad``` populated during a call to ```backward()```. To get grad populated for non-leaf Tensors, you can use ```retain_grad()```.

```python

>>> a = torch.rand(10, requires_grad=True)
>>> a.is_leaf
True
>>> b = torch.rand(10, requires_grad=True).cuda()
>>> b.is_leaf
False
# b was created by the operation that cast a cpu Tensor into a cuda Tensor
>>> c = torch.rand(10, requires_grad=True) + 2
>>> c.is_leaf
False
# c was created by the addition operation
>>> d = torch.rand(10).cuda()
>>> d.is_leaf
True
# d does not require gradients and so has no operation creating it (that is tracked by the autograd engine)
>>> e = torch.rand(10).cuda().requires_grad_()
>>> e.is_leaf
True
# e requires gradients and has no operations creating it
>>> f = torch.rand(10, requires_grad=True, device="cuda")
>>> f.is_leaf
True
# f requires grad, has no operation creating it

```

---

**torch.squeeze(input, dim=None, out=None)**

Returns a tensor with all the dimensions of input of size 1 removed.

For example, if input is of shape:(A×1×B×C×1×D) then the out tensor will be of shape: (A×B×C×D) .

When dim is given, a squeeze operation is done only in the given dimension. If input is of shape: (A×1×B) , squeeze(input, 0) leaves the tensor unchanged, but squeeze(input, 1) will squeeze the tensor to the shape (A×B) .

In [55]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [57]:
x.squeeze().size()

torch.Size([2, 2, 2])

In [86]:
y = torch.ones(2,2)

In [76]:
z.size()

torch.Size([2, 1, 2, 1, 2])

**torch.unsqueeze(input, dim)**

Returns a new tensor with a dimension of size one inserted at the specified position.

The returned tensor shares the same underlying data with this tensor.

A dim value within the range ```[-input.dim() - 1, input.dim() + 1)]``` can be used. Negative dim will correspond to unsqueeze() applied at ```dim = dim + input.dim() + 1.```

In [103]:
p = y.unsqueeze(dim=1)

In [104]:
p

tensor([[[1., 1.]],

        [[1., 1.]]])

In [105]:
p.shape

torch.Size([2, 1, 2])